// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYtr2qsQkl6Be3zF2fhpJNMCxlvaZH4HI',
    appId: '1:748090900792:web:b8b4bfdc90ca355e80c1cd',
    messagingSenderId: '748090900792',
    projectId: 'voiceup-15c48',
    authDomain: 'voiceup-15c48.firebaseapp.com',
    storageBucket: 'voiceup-15c48.appspot.com',
    measurementId: 'G-1ECN51EC54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfhsYCouWs6X7rKc9TUoJZFqu11_OymY',
    appId: '1:748090900792:android:96d71cc8fcf513c280c1cd',
    messagingSenderId: '748090900792',
    projectId: 'voiceup-15c48',
    storageBucket: 'voiceup-15c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd8YthcQA7pNSMmoCB-u84V9zsrJMCfN4',
    appId: '1:748090900792:ios:9640c20f78614de880c1cd',
    messagingSenderId: '748090900792',
    projectId: 'voiceup-15c48',
    storageBucket: 'voiceup-15c48.appspot.com',
    iosClientId: '748090900792-e18qu0u6fdcudf00bmch2rkedb07mus2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbvapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd8YthcQA7pNSMmoCB-u84V9zsrJMCfN4',
    appId: '1:748090900792:ios:9640c20f78614de880c1cd',
    messagingSenderId: '748090900792',
    projectId: 'voiceup-15c48',
    storageBucket: 'voiceup-15c48.appspot.com',
    iosClientId: '748090900792-e18qu0u6fdcudf00bmch2rkedb07mus2.apps.googleusercontent.com',
    iosBundleId: 'com.example.gbvapp',
  );
}
